### ISSUE TITLE
FileNotFoundError: File (/work/point2cad/tmp.obj) not found

### ISSUE THREAD

**Issue by anikimmel** [YujiaLiu76/point2cad#12]
Trying to run the docker container on windows using default command provided, getting this error:
docker run -it --rm --gpus=all -v .:/work/point2cad point2cad python -m point2cad.main

![image](https://github.com/user-attachments/assets/ad6236ab-98d3-40af-ada8-17084c9ff9d0)

Stack trace:

`Fitting surfaces:  31%|████████████████████▋                                             | 5/16 [01:42<04:49, 26.31s/it]2024-08-25 18:24:21.016 ( 117.939s) [    7F4BC973B700]   vtkXMLDataReader.cxx:396    ERR| vtkXMLPolyDataReader (0x7f4bc40031e0): Cannot read point data array "Normals" from PointData in piece 0.  The data array in the element may be too short.
ERROR:root:Cannot read point data array "Normals" from PointData in piece 0.  The data array in the element may be too short.
Fitting surfaces:  44%|████████████████████████████▉                                     | 7/16 [02:00<02:34, 17.18s/it]
concurrent.futures.process._RemoteTraceback:
"""
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/concurrent/futures/process.py", line 239, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/work/point2cad/point2cad/fitting_one_surface.py", line 143, in process_one_surface
    pred_mesh = pv.read("tmp.obj")
  File "/opt/conda/lib/python3.7/site-packages/pyvista/utilities/fileio.py", line 167, in read
    raise FileNotFoundError(f'File ({filename}) not found')
FileNotFoundError: File (/work/point2cad/tmp.obj) not found
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/conda/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/work/point2cad/point2cad/main.py", line 87, in <module>
    out_meshes = fn_process(cfg, uniq_labels, points, labels, device)
  File "/work/point2cad/point2cad/main.py", line 26, in process_multiprocessing
    out_meshes[idx] = future.result()
  File "/opt/conda/lib/python3.7/concurrent/futures/_base.py", line 428, in result
    return self.__get_result()
  File "/opt/conda/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
FileNotFoundError: File (/work/point2cad/tmp.obj) not found`

**Comment by seeker1998** [comment]
Is this problem solved? Can you help me? Thanks

**Comment by VDhinakar** [comment]
I was facing the same issue. I have 3060ti GPU. I ran the code with this configuration ` python -m point2cad.main --max_parallel_surfaces 1` and it ran successfully.
[https://i.vgy.me/RyfNJU.png](url)
